#!/usr/bin/env python
# -*- coding:utf-8 -*-

# This file is part of the lily-fonts project
# https://github.com/openlilylib/lily-fonts
#
# Copyright (c) 2015 by Urs Liska (ul@openlilylib.org)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# See http://www.gnu.org/licenses/ for more information.

from __future__ import unicode_literals

import os
import sys
import shutil
import zipfile

from util.config import Config
from util.fonts import Fonts
from util import error

def main():
    Config.read_args()
    fonts = Fonts()
    fonts.handle_fonts()

    sys.exit(0)

# ####################################
# Finally launch the program
if __name__ == "__main__":
    main()
